# This is just an example workflow for continuous deployment.
# You should customize it to meet your own requirements.
trigger:
# When new commits are pushed onto the main branch.
- main 

pool:
  vmImage: ubuntu-latest

steps:
# Setup environment.
- task: NodeTool@0
  inputs:
    versionSpec: '14.17.0'
    checkLatest: true

- task: Bash@3
  env:
    TEAMSFX_ENV_NAME: dev
  inputs:
    targetType: 'inline'
    script: |
      set -evuxo pipefail
      echo pipeline